name = "EndlessTesting"
uuid = "a2d587bb-f694-4225-843f-aa0665c48f41"
authors = ["woclass <git@wo-class.cn> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
