name = "TheMissingDoc4Julia"
uuid = "b3de0d96-2cd1-4157-8b45-2c2f2873eb80"
authors = ["woclass <git@wo-class.cn> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
